"""empty message

Revision ID: 8162f4d8d850
Revises: a7548bda3777
Create Date: 2023-07-28 12:15:02.543693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8162f4d8d850'
down_revision = 'a7548bda3777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=False),
    sa.Column('eye_color', sa.String(length=250), nullable=False),
    sa.Column('skin_color', sa.String(), nullable=False),
    sa.Column('birth_year', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('homeworld', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
